name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
   - uses: actions/checkout@v2
#
 #     - name: Get Latest BYOND version.txt
   #     run: wget https://secure.byond.com/download/version.txt

    #  - name: Set BYOND_VERSION
     #   run: echo ::set-env name=BYOND_VERSION::$(cat version.txt | awk '{$1=$1};1')

      #- name: Set BYOND_MAJOR
       # run: echo ::set-env name=BYOND_MAJOR::$(cut -d'.' -f1 <<< $BYOND_VERSION)

#      - name: Set BYOND_MINOR
 #       run: echo ::set-env name=BYOND_MINOR::$(cut -d'.' -f2 <<< $BYOND_VERSION)

  #    - name: Build and Publish to Registry
   #     uses: elgohr/Publish-Docker-Github-Action@master
    #    with:
     #     name: damnationstation13/byond
      #    username: ${{ secrets.DOCKER_USERNAME }}
       #   password: ${{ secrets.DOCKER_PASSWORD }}
        #  dockerfile: Dockerfile
         # buildargs: BYOND_MAJOR,BYOND_MINOR
          #tags: "latest,${{ env.BYOND_VERSION }}"
        #  cache: true
